// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"canteen-app/internal/domain/auth"
	"canteen-app/internal/domain/user"

	mock "github.com/stretchr/testify/mock"
)

// NewAuthUseCase creates a new instance of AuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUseCase {
	mock := &AuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthUseCase is an autogenerated mock type for the AuthUseCase type
type AuthUseCase struct {
	mock.Mock
}

type AuthUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthUseCase) EXPECT() *AuthUseCase_Expecter {
	return &AuthUseCase_Expecter{mock: &_m.Mock}
}

// GetUserByLogin provides a mock function for the type AuthUseCase
func (_mock *AuthUseCase) GetUserByLogin(login string) (*user.User, error) {
	ret := _mock.Called(login)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByLogin")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*user.User, error)); ok {
		return returnFunc(login)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *user.User); ok {
		r0 = returnFunc(login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthUseCase_GetUserByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByLogin'
type AuthUseCase_GetUserByLogin_Call struct {
	*mock.Call
}

// GetUserByLogin is a helper method to define mock.On call
//   - login string
func (_e *AuthUseCase_Expecter) GetUserByLogin(login interface{}) *AuthUseCase_GetUserByLogin_Call {
	return &AuthUseCase_GetUserByLogin_Call{Call: _e.mock.On("GetUserByLogin", login)}
}

func (_c *AuthUseCase_GetUserByLogin_Call) Run(run func(login string)) *AuthUseCase_GetUserByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthUseCase_GetUserByLogin_Call) Return(user1 *user.User, err error) *AuthUseCase_GetUserByLogin_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *AuthUseCase_GetUserByLogin_Call) RunAndReturn(run func(login string) (*user.User, error)) *AuthUseCase_GetUserByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type AuthUseCase
func (_mock *AuthUseCase) Login(login string, password string) (*auth.Tokens, error) {
	ret := _mock.Called(login, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *auth.Tokens
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*auth.Tokens, error)); ok {
		return returnFunc(login, password)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *auth.Tokens); ok {
		r0 = returnFunc(login, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Tokens)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(login, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthUseCase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthUseCase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - login string
//   - password string
func (_e *AuthUseCase_Expecter) Login(login interface{}, password interface{}) *AuthUseCase_Login_Call {
	return &AuthUseCase_Login_Call{Call: _e.mock.On("Login", login, password)}
}

func (_c *AuthUseCase_Login_Call) Run(run func(login string, password string)) *AuthUseCase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthUseCase_Login_Call) Return(tokens *auth.Tokens, err error) *AuthUseCase_Login_Call {
	_c.Call.Return(tokens, err)
	return _c
}

func (_c *AuthUseCase_Login_Call) RunAndReturn(run func(login string, password string) (*auth.Tokens, error)) *AuthUseCase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type AuthUseCase
func (_mock *AuthUseCase) Refresh(refreshToken string) (*auth.Tokens, error) {
	ret := _mock.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *auth.Tokens
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*auth.Tokens, error)); ok {
		return returnFunc(refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *auth.Tokens); ok {
		r0 = returnFunc(refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Tokens)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthUseCase_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type AuthUseCase_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - refreshToken string
func (_e *AuthUseCase_Expecter) Refresh(refreshToken interface{}) *AuthUseCase_Refresh_Call {
	return &AuthUseCase_Refresh_Call{Call: _e.mock.On("Refresh", refreshToken)}
}

func (_c *AuthUseCase_Refresh_Call) Run(run func(refreshToken string)) *AuthUseCase_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthUseCase_Refresh_Call) Return(tokens *auth.Tokens, err error) *AuthUseCase_Refresh_Call {
	_c.Call.Return(tokens, err)
	return _c
}

func (_c *AuthUseCase_Refresh_Call) RunAndReturn(run func(refreshToken string) (*auth.Tokens, error)) *AuthUseCase_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type AuthUseCase
func (_mock *AuthUseCase) Register(login string, password string, name string, surname string, role string) (*auth.Tokens, error) {
	ret := _mock.Called(login, password, name, surname, role)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *auth.Tokens
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, string) (*auth.Tokens, error)); ok {
		return returnFunc(login, password, name, surname, role)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, string) *auth.Tokens); ok {
		r0 = returnFunc(login, password, name, surname, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Tokens)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, string, string) error); ok {
		r1 = returnFunc(login, password, name, surname, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthUseCase_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AuthUseCase_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - login string
//   - password string
//   - name string
//   - surname string
//   - role string
func (_e *AuthUseCase_Expecter) Register(login interface{}, password interface{}, name interface{}, surname interface{}, role interface{}) *AuthUseCase_Register_Call {
	return &AuthUseCase_Register_Call{Call: _e.mock.On("Register", login, password, name, surname, role)}
}

func (_c *AuthUseCase_Register_Call) Run(run func(login string, password string, name string, surname string, role string)) *AuthUseCase_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *AuthUseCase_Register_Call) Return(tokens *auth.Tokens, err error) *AuthUseCase_Register_Call {
	_c.Call.Return(tokens, err)
	return _c
}

func (_c *AuthUseCase_Register_Call) RunAndReturn(run func(login string, password string, name string, surname string, role string) (*auth.Tokens, error)) *AuthUseCase_Register_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function for the type AuthUseCase
func (_mock *AuthUseCase) RevokeRefreshToken(refreshToken string) error {
	ret := _mock.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthUseCase_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type AuthUseCase_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - refreshToken string
func (_e *AuthUseCase_Expecter) RevokeRefreshToken(refreshToken interface{}) *AuthUseCase_RevokeRefreshToken_Call {
	return &AuthUseCase_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", refreshToken)}
}

func (_c *AuthUseCase_RevokeRefreshToken_Call) Run(run func(refreshToken string)) *AuthUseCase_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthUseCase_RevokeRefreshToken_Call) Return(err error) *AuthUseCase_RevokeRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthUseCase_RevokeRefreshToken_Call) RunAndReturn(run func(refreshToken string) error) *AuthUseCase_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
