// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewValidator creates a new instance of Validator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Validator {
	mock := &Validator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Validator is an autogenerated mock type for the Validator type
type Validator struct {
	mock.Mock
}

type Validator_Expecter struct {
	mock *mock.Mock
}

func (_m *Validator) EXPECT() *Validator_Expecter {
	return &Validator_Expecter{mock: &_m.Mock}
}

// Struct provides a mock function for the type Validator
func (_mock *Validator) Struct(v any) error {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Struct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Validator_Struct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Struct'
type Validator_Struct_Call struct {
	*mock.Call
}

// Struct is a helper method to define mock.On call
//   - v any
func (_e *Validator_Expecter) Struct(v interface{}) *Validator_Struct_Call {
	return &Validator_Struct_Call{Call: _e.mock.On("Struct", v)}
}

func (_c *Validator_Struct_Call) Run(run func(v any)) *Validator_Struct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Validator_Struct_Call) Return(err error) *Validator_Struct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Validator_Struct_Call) RunAndReturn(run func(v any) error) *Validator_Struct_Call {
	_c.Call.Return(run)
	return _c
}
